from _typeshed import Incomplete
from huey import Huey

from django_huey.exceptions import ConfigurationError as ConfigurationError

default_backend_path: str

def get_backend(import_path=...): ...

class DjangoHueySettingsReader:
    hueys_setting: dict[str, Huey]
    default_queue: str | None
    hueys: Incomplete
    def __init__(self, hueys_setting) -> None: ...
    def configure(self) -> None: ...
    def include(self, queues) -> None: ...
    def get_queue(self, queue: str | None) -> Huey: ...
    def get_queue_name(self, queue_name: str | None) -> str: ...
